// client/src/pages/settings/swatchSettings.tsx
import { useTranslate } from "@refinedev/core";
import { Button, Col, Form, Row, Select, Typography, message } from "antd";
import { useEffect } from "react";
import SwatchPreview from "../../components/swatchPreview";
import { parseStringSettingValue, useGetSettings, useSetSetting } from "../../utils/querySettings";
import {
  DEFAULT_SWATCH_STYLE_KEY,
  SWATCH_STYLES,
  SwatchInput,
  buildSwatchLayoutForStyle,
  getSwatchStyle,
} from "../../utils/swatch";

const { Text } = Typography;

// Two demo filaments so the preview shows both marking colors: black text on a
// light filament and white text (with inverted QR) on a dark one.
const SAMPLE_LIGHT: SwatchInput = {
  id: 42,
  name: "Sunrise Yellow",
  vendorName: "Vendor",
  material: "PLA",
  diameterMm: 1.75,
  weightG: 1000,
  extruderTempC: 215,
  bedTempC: 60,
  articleNumber: "ART-0042",
  colorHexes: ["f5c211"],
  qrPayload: "WEB+SPOOLMAN:F-42",
};
const SAMPLE_DARK: SwatchInput = {
  ...SAMPLE_LIGHT,
  id: 7,
  name: "Galaxy Black",
  material: "PETG",
  extruderTempC: 240,
  bedTempC: 80,
  articleNumber: "ART-0007",
  colorHexes: ["23233a"],
  qrPayload: "WEB+SPOOLMAN:F-7",
};

export function SwatchSettings() {
  const settings = useGetSettings();
  const setSwatchStyle = useSetSetting("swatch_style");
  const [form] = Form.useForm();
  const [messageApi, contextHolder] = message.useMessage();
  const t = useTranslate();

  useEffect(() => {
    if (settings.data) {
      form.setFieldsValue({
        swatch_style: getSwatchStyle(parseStringSettingValue(settings.data.swatch_style?.value)).key,
      });
    }
  }, [settings.data, form]);

  useEffect(() => {
    if (setSwatchStyle.isSuccess) {
      messageApi.success(t("notifications.saveSuccessful"));
    }
  }, [setSwatchStyle.isSuccess, messageApi, t]);

  const selectedStyleKey: string = Form.useWatch("swatch_style", form) ?? DEFAULT_SWATCH_STYLE_KEY;

  const onFinish = (values: { swatch_style: string }) => {
    if (settings.data?.swatch_style?.value !== JSON.stringify(values.swatch_style)) {
      setSwatchStyle.mutate(values.swatch_style);
    }
  };

  return (
    <>
      <Form form={form} labelCol={{ span: 8 }} wrapperCol={{ span: 16 }} onFinish={onFinish}>
        <Form.Item
          label={t("settings.swatch.default_style.label")}
          tooltip={t("settings.swatch.default_style.tooltip")}
          name="swatch_style"
        >
          <Select
            options={SWATCH_STYLES.map((style) => ({
              value: style.key,
              label: t(`filament.swatch.styles.${style.key}`, { defaultValue: style.name }),
            }))}
          />
        </Form.Item>

        <Form.Item wrapperCol={{ offset: 8, span: 16 }}>
          <Button type="primary" htmlType="submit" loading={settings.isFetching || setSwatchStyle.isPending}>
            {t("buttons.save")}
          </Button>
        </Form.Item>
      </Form>
      <Text type="secondary">{t("settings.swatch.preview_description")}</Text>
      <Row gutter={[16, 16]} style={{ marginTop: 16 }}>
        <Col xs={24} lg={12}>
          <SwatchPreview layout={buildSwatchLayoutForStyle(SAMPLE_LIGHT, selectedStyleKey)} />
        </Col>
        <Col xs={24} lg={12}>
          <SwatchPreview layout={buildSwatchLayoutForStyle(SAMPLE_DARK, selectedStyleKey)} />
        </Col>
      </Row>
      {contextHolder}
    </>
  );
}

// client_v2/src/lib/ng/components/swatch/SwatchSettings.svelte
<script lang="ts">
	/**
	 * Spoolman NG fork addition (#415 step 3): the default swatch style, with a preview on two
	 * example filaments -- one light, one dark -- so both marking colours show. Ported from the
	 * classic client's `pages/settings/swatchSettings.tsx`.
	 *
	 * Renders nothing for a non-administrator, like every fork settings panel: the write would
	 * be refused. Saves on change, optimistically with a rollback, like the unit-scaling switch.
	 */
	import NgSettingsSection from '$lib/ng/components/NgSettingsSection.svelte';
	import SwatchPreview from './SwatchPreview.svelte';
	import { ng } from '$lib/ng/i18n';
	import { toasts } from '$lib/stores/toasts.svelte';
	import { currentUserIsAdmin } from '$lib/ng/me';
	import { apiErrorMessage } from '$lib/ng/errors';
	import { SWATCH_STYLES, buildSwatchLayoutForStyle, getSwatchStyle, type SwatchInput } from '$lib/ng/swatch';
	import { loadSwatchStyle, saveSwatchStyle } from '$lib/ng/swatchStyleSetting';
	import { swatchStyleName } from '$lib/ng/swatchText';
	import * as m from '$lib/paraglide/messages';

	// The classic client's two example filaments, so the preview reads the same in both.
	const SAMPLE_LIGHT: SwatchInput = {
		id: 42,
		name: 'Sunrise Yellow',
		vendorName: 'Vendor',
		material: 'PLA',
		diameterMm: 1.75,
		weightG: 1000,
		extruderTempC: 215,
		bedTempC: 60,
		articleNumber: 'ART-0042',
		colorHexes: ['f5c211'],
		qrPayload: 'WEB+SPOOLMAN:F-42'
	};
	const SAMPLE_DARK: SwatchInput = {
		...SAMPLE_LIGHT,
		id: 7,
		name: 'Galaxy Black',
		material: 'PETG',
		extruderTempC: 240,
		bedTempC: 80,
		articleNumber: 'ART-0007',
		colorHexes: ['23233a'],
		qrPayload: 'WEB+SPOOLMAN:F-7'
	};

	let show = $state(false);
	let styleKey = $state(getSwatchStyle(null).key);

	$effect(() => {
		currentUserIsAdmin()
			.then((admin) => (show = admin))
			.catch(() => {});
		const ctrl = new AbortController();
		loadSwatchStyle(ctrl.signal).then((k) => (styleKey = k));
		return () => ctrl.abort();
	});

	async function choose(key: string) {
		const previous = styleKey;
		styleKey = key;
		try {
			await saveSwatchStyle(key);
			toasts.success(m['notifications.saveSuccessful']());
		} catch (e) {
			styleKey = previous;
			toasts.error(apiErrorMessage(e));
		}
	}
</script>

{#if show}
	<NgSettingsSection title={ng.settings_swatch_tab()}>
		<label class="row">
			<span class="lbl" title={ng.settings_swatch_default_style_tooltip()}
				>{ng.settings_swatch_default_style_label()}</span
			>
			<select class="sel" value={styleKey} onchange={(e) => choose(e.currentTarget.value)}>
				{#each SWATCH_STYLES as s (s.key)}
					<option value={s.key}>{swatchStyleName(s.key)}</option>
				{/each}
			</select>
		</label>
		<p class="intro">{ng.settings_swatch_preview_description()}</p>
		<div class="samples">
			{#each [SAMPLE_LIGHT, SAMPLE_DARK] as sample (sample.id)}
				<div class="sample">
					<SwatchPreview
						layout={buildSwatchLayoutForStyle(sample, styleKey)}
						label={`${swatchStyleName(styleKey)} · ${sample.name}`}
					/>
				</div>
			{/each}
		</div>
	</NgSettingsSection>
{/if}

<style>
	.row {
		display: flex;
		align-items: center;
		gap: 12px;
		font-size: 13px;
	}
	.lbl {
		color: var(--text-2);
	}
	.sel {
		background: var(--input-bg);
		border: 1px solid var(--border-input);
		border-radius: var(--radius-sm);
		color: var(--text);
		padding: 5px 8px;
		font-size: 13px;
	}
	.intro {
		font-size: 12px;
		color: var(--text-muted);
		margin: 10px 0 6px;
	}
	.samples {
		display: flex;
		flex-wrap: wrap;
		gap: 16px;
	}
	.sample {
		flex: 1 1 200px;
		max-width: 320px;
	}
</style>
