// client/src/pages/orders/newOrderModal.tsx
import { DeleteOutlined, PlusOutlined } from "@ant-design/icons";
import { useCreate, useInvalidate, useTranslate } from "@refinedev/core";
import { AutoComplete, Button, Col, DatePicker, Form, Input, InputNumber, message, Modal, Row, Select } from "antd";
import { useForm } from "antd/es/form/Form";
import dayjs, { Dayjs } from "dayjs";
import utc from "dayjs/plugin/utc";
import { useEffect, useMemo, useRef, useState } from "react";
import SpoolIcon from "../../components/spoolIcon";
import { DATE_FORMAT } from "../../utils/dateFormat";
import { searchMatches } from "../../utils/filtering";
import { IFilament } from "../filaments/model";
import { FilamentColor, filamentColorObj, formatFilamentLabel } from "../spools/functions";
import { buildNewOrderBody, OrderLineInput } from "./orderBody";
import { useShops } from "./useShops";
import "./orders.css";

dayjs.extend(utc);

interface NewOrderFormValues {
  shop_name?: string;
  ordered_at: Dayjs;
  order_number?: string;
  url?: string;
  comment?: string;
}

// A draft line in the builder. `key` is a stable identity for React/edit tracking; `filament_id`
// is undefined until the user picks one (an incomplete line is dropped on save).
interface DraftLine {
  key: number;
  filament_id?: number;
  quantity: number;
  price_per_unit?: number;
}

interface Props {
  open: boolean;
  filaments: IFilament[];
  onClose: () => void;
  onSuccess: () => void;
}

/**
 * From-scratch "New order" builder (#324): opened by the Orders page's "+ New order" button, which
 * used to be a disabled placeholder — orders were only born from the Low Stock flows. It mirrors the
 * order details/edit modal's header surface (shop AutoComplete, order-date DatePicker, order number,
 * url, comment) but, since there is no existing order to seed lines from, adds a filament picker +
 * lines editor: each line chooses a filament and its quantity/price, with add/remove. On save a
 * POST /order is built by `buildNewOrderBody` (create semantics — blank optional fields omitted).
 */
export function NewOrderModal({ open, filaments, onClose, onSuccess }: Props) {
  const t = useTranslate();
  const [form] = useForm<NewOrderFormValues>();
  const { shops, ensureShop } = useShops();
  const { mutate: createOrder, mutation } = useCreate();
  const invalidate = useInvalidate();
  const [submitting, setSubmitting] = useState(false);
  const [lines, setLines] = useState<DraftLine[]>([]);
  // Monotonic key source for new draft lines (see DraftLine.key). A ref, not state, so bumping it
  // never triggers a render on its own.
  const nextKey = useRef(0);
  // Guards initialization to the open:false→true transition only (same convention as
  // createOrderModal.tsx / orderDetailsModal.tsx) — a background refetch of the filament list while
  // this stays open must not reset the form or wipe lines the user already built.
  const wasOpenRef = useRef(false);

  useEffect(() => {
    if (open && !wasOpenRef.current) {
      form.resetFields();
      form.setFieldsValue({ ordered_at: dayjs() });
      setLines([{ key: 0, quantity: 1 }]);
      nextKey.current = 1;
    }
    wasOpenRef.current = open;
  }, [open, form]);

  const shopOptions = shops.map((s) => ({ value: s.name }));

  // Internal filaments only — an order line references a real filament row. Same label/colour
  // treatment as the spool-create picker (functions.tsx), sorted case-insensitively by label.
  const filamentOptions = useMemo(
    () =>
      filaments
        .map((f) => ({
          label: formatFilamentLabel(f.name ?? `ID ${f.id}`, f.diameter, f.vendor?.name, f.material, f.weight),
          value: f.id,
          colorObj: filamentColorObj(
            f.color_hex,
            f.multi_color_hexes ? f.multi_color_hexes.split(",") : undefined,
            f.multi_color_direction,
          ),
        }))
        .sort((a, b) => a.label.localeCompare(b.label, undefined, { sensitivity: "base" })),
    [filaments],
  );

  const addLine = () => {
    const key = nextKey.current++;
    setLines((prev) => [...prev, { key, quantity: 1 }]);
  };
  const removeLine = (key: number) => setLines((prev) => prev.filter((l) => l.key !== key));
  const updateLine = (key: number, patch: Partial<DraftLine>) =>
    setLines((prev) => prev.map((l) => (l.key === key ? { ...l, ...patch } : l)));

  // An order needs at least one line with a filament actually chosen; the OK button gates on this.
  const hasValidLine = lines.some((l) => l.filament_id != null);

  const onFinish = async (values: NewOrderFormValues) => {
    const orderLines: OrderLineInput[] = lines
      .filter((l): l is DraftLine & { filament_id: number } => l.filament_id != null)
      .map((l) => {
        const line: OrderLineInput = { filament_id: l.filament_id, quantity: l.quantity };
        if (l.price_per_unit !== undefined) line.price_per_unit = l.price_per_unit;
        return line;
      });
    if (orderLines.length === 0) {
      message.error(t("orders.no_lines"));
      return;
    }
    setSubmitting(true);
    try {
      const name = values.shop_name?.trim();
      const shopId = name ? await ensureShop(name) : undefined;
      const body = buildNewOrderBody({
        orderedAt: values.ordered_at.utc().format(),
        lines: orderLines,
        shopId,
        orderNumber: values.order_number?.trim(),
        url: values.url?.trim(),
        comment: values.comment?.trim(),
      });
      createOrder(
        { resource: "order", values: body, successNotification: false },
        {
          onSuccess: () => {
            invalidate({ resource: "filament", invalidates: ["list"] });
            invalidate({ resource: "order", invalidates: ["list"] });
            setSubmitting(false);
            onSuccess();
            onClose();
          },
          onError: () => {
            setSubmitting(false);
            message.error(t("orders.create_error"));
          },
        },
      );
    } catch {
      setSubmitting(false);
      message.error(t("orders.create_error"));
    }
  };

  return (
    <Modal
      title={t("orders.new_order_title")}
      open={open}
      onCancel={onClose}
      onOk={form.submit}
      okText={t("orders.create_order")}
      okButtonProps={{ disabled: !hasValidLine }}
      confirmLoading={submitting || mutation.isPending}
      destroyOnClose
      width={640}
    >
      <Form form={form} layout="vertical" onFinish={onFinish} initialValues={{ ordered_at: dayjs() }}>
        <Row gutter={16}>
          <Col xs={24} md={12}>
            <Form.Item name="shop_name" label={t("orders.shop")}>
              <AutoComplete
                options={shopOptions}
                filterOption={(input, option) => (option?.value ?? "").toLowerCase().includes(input.toLowerCase())}
                placeholder={t("orders.shop_placeholder")}
              />
            </Form.Item>
          </Col>
          <Col xs={24} md={12}>
            <Form.Item name="ordered_at" label={t("orders.order_date")} rules={[{ required: true }]}>
              <DatePicker style={{ width: "100%" }} format={DATE_FORMAT} allowClear={false} />
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={16}>
          <Col xs={24} md={12}>
            <Form.Item name="order_number" label={t("orders.order_number_field")}>
              <Input maxLength={256} placeholder="e.g. 3DJ-84302" />
            </Form.Item>
          </Col>
          <Col xs={24} md={12}>
            <Form.Item name="url" label={t("orders.url")}>
              <Input placeholder="https://..." maxLength={1024} />
            </Form.Item>
          </Col>
        </Row>
        <Form.Item name="comment" label={t("orders.comment")}>
          <Input.TextArea maxLength={1024} rows={2} />
        </Form.Item>
      </Form>
      <div className="order-details-lines">
        <div className="order-details-lines-header">{t("orders.lines_summary_title")}</div>
        {lines.map((line) => (
          <div key={line.key} className="order-details-line">
            <Select
              className="new-order-line-filament"
              showSearch
              value={line.filament_id}
              placeholder={t("orders.select_filament")}
              aria-label={t("spool.fields.filament")}
              options={filamentOptions}
              filterOption={(input, option) => typeof option?.label === "string" && searchMatches(input, option.label)}
              optionRender={(oriOption) => (
                <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
                  <span style={{ display: "inline-flex", flex: "0 0 auto", fontSize: "0.6em" }}>
                    <SpoolIcon color={(oriOption.data as { colorObj?: FilamentColor }).colorObj} no_margin />
                  </span>
                  <span style={{ overflow: "hidden", textOverflow: "ellipsis" }}>{oriOption.label}</span>
                </div>
              )}
              onChange={(v) => updateLine(line.key, { filament_id: v ?? undefined })}
            />
            <InputNumber
              min={1}
              value={line.quantity}
              aria-label={t("orders.quantity")}
              onChange={(v) => updateLine(line.key, { quantity: v ?? 1 })}
            />
            <InputNumber
              min={0}
              value={line.price_per_unit}
              placeholder="21.90"
              aria-label={t("orders.price_per_unit")}
              onChange={(v) => updateLine(line.key, { price_per_unit: v ?? undefined })}
            />
            <Button
              type="text"
              icon={<DeleteOutlined />}
              aria-label={t("orders.remove_line")}
              onClick={() => removeLine(line.key)}
            />
          </div>
        ))}
        <Button type="dashed" icon={<PlusOutlined />} onClick={addLine} block>
          {t("orders.add_line")}
        </Button>
      </div>
    </Modal>
  );
}

export default NewOrderModal;

// client_v2/src/lib/ng/components/NewOrderModal.svelte
<script lang="ts">
	// From-scratch "New order" builder (#324) — ported from client/src/pages/orders/newOrderModal.tsx:
	// opened by the Orders page's "+ New order" button. Mirrors the order details/edit modal's header
	// surface (shop Combobox, order-date field, order number, url, comment) but, since there is no
	// existing order to seed lines from, adds a filament picker + lines editor: each line chooses a
	// filament and its quantity/price, with add/remove. On save a POST /order is built by
	// `buildNewOrderBody` (create semantics — blank optional fields omitted, unlike the edit modal's
	// PATCH which sends explicit nulls; see orderEditBody.ts's docstring for why those differ).
	//
	// This client has no generic id-keyed searchable-select component (Combobox only round-trips a
	// plain string value against a string option list, which fits a shop *name* but not a filament
	// *id*), so the picker below is a plain `<select>` — the same widget already used for a
	// small enum choice (ExtraFieldInput.svelte's `.sel`) and for ArriveModal's location picker.
	// It loses the antd original's inline colour swatch per option (native `<option>` can't render
	// arbitrary markup) but keeps the actual feature: choosing a filament by name, sorted the same way.
	//
	// Mounted only while actually open (`{#if creating}<NewOrderModal .../>{/if}`), same
	// conditionally-mounted convention as MarkOrderedDialog/CreateOrderModal — so every `$state`
	// below starts fresh each time and there is nothing to reset on reopen.
	import Button from '$components/Button.svelte';
	import Field from '$components/Field.svelte';
	import FieldGrid from '$components/FieldGrid.svelte';
	import Combobox from '$components/Combobox.svelte';
	import NumberInput from '$components/NumberInput.svelte';
	import DateTimeField from '$components/DateTimeField.svelte';
	import EditableField from '$components/EditableField.svelte';
	import X from '@lucide/svelte/icons/x';
	import Plus from '@lucide/svelte/icons/plus';
	import Trash2 from '@lucide/svelte/icons/trash-2';
	import * as m from '$lib/paraglide/messages';
	import { ng } from '$lib/ng/i18n';
	import { listShops, ensureShop, createOrder } from '$lib/ng/api';
	import { buildNewOrderBody, type OrderLineInput } from '$lib/ng/orderBody';
	import { getFilamentName } from '$lib/ng/analytics';
	import { toasts } from '$lib/stores/toasts.svelte';
	import type { ForkFilament } from '$lib/ng/types';
	import type { Vendor } from '$lib/types';

	interface Props {
		filaments: ForkFilament[];
		vendors: Vendor[];
		onclose: () => void;
		onsuccess: () => void;
	}
	let { filaments, vendors, onclose, onsuccess }: Props = $props();

	// A draft line in the builder. `key` is a stable identity for #each/edit tracking; `filamentId`
	// is undefined until the user picks one (an incomplete line is dropped on save). Quantity/price
	// are plain numbers, updated via `updateLine` — the same NumberInput "commit" mode
	// (value+onchange, see NumberInput.svelte's own doc comment) OrderDetailsModal/ArriveModal use
	// for their own per-line quantity fields.
	interface DraftLine {
		key: number;
		filamentId?: string;
		quantity: number;
		pricePerUnit?: number;
	}

	let shopName = $state('');
	let shops = $state<string[]>([]);
	let orderedAt = $state<string | undefined>(new Date().toISOString());
	let orderNumber = $state('');
	let url = $state('');
	let comment = $state('');
	let lines = $state<DraftLine[]>([{ key: 0, quantity: 1 }]);
	let nextKey = 1;
	let submitting = $state(false);

	// A $derived, not a one-time snapshot: unlike the dialog's own header/lines state, there's no
	// reason to freeze this against a live filament rename while the picker is open.
	let filamentOptions = $derived(
		[...filaments]
			.map((f) => ({ id: f.id, label: getFilamentName(f, vendors) }))
			.sort((a, b) => a.label.localeCompare(b.label, undefined, { sensitivity: 'base' }))
	);

	// An order needs at least one line with a filament actually chosen; the submit button gates on this.
	let hasValidLine = $derived(lines.some((l) => l.filamentId != null));

	function addLine() {
		lines = [...lines, { key: nextKey++, quantity: 1 }];
	}
	function removeLine(key: number) {
		lines = lines.filter((l) => l.key !== key);
	}
	function updateLine(key: number, patch: Partial<DraftLine>) {
		lines = lines.map((l) => (l.key === key ? { ...l, ...patch } : l));
	}

	let dialog = $state<HTMLDivElement>();
	let opener: HTMLElement | null = null;
	$effect(() => {
		opener = document.activeElement as HTMLElement | null;
		dialog?.focus();
		listShops()
			.then((s) => (shops = s.map((sh) => sh.name)))
			.catch(() => (shops = []));
		return () => opener?.focus();
	});

	function close() {
		if (!submitting) onclose();
	}

	async function submit() {
		if (submitting || !orderedAt) return;
		const orderLines: OrderLineInput[] = lines
			.filter((l): l is DraftLine & { filamentId: string } => l.filamentId != null)
			.map((l) => ({ filamentId: l.filamentId, quantity: l.quantity, pricePerUnit: l.pricePerUnit }));
		if (orderLines.length === 0) {
			toasts.error(ng.orders_no_lines());
			return;
		}
		submitting = true;
		try {
			const name = shopName.trim();
			const shopId = name ? await ensureShop(name) : undefined;
			const body = buildNewOrderBody({
				orderedAt,
				lines: orderLines,
				shopId,
				orderNumber: orderNumber.trim() || undefined,
				url: url.trim() || undefined,
				comment: comment.trim() || undefined
			});
			await createOrder(body);
			onsuccess();
			onclose();
		} catch (e) {
			// Includes buildNewOrderBody's own thrown error for a filament id that can't round-trip
			// as an integer -- surfaced as a toast rather than swallowed.
			console.error('Failed to create order', e);
			toasts.error(ng.orders_create_error());
		} finally {
			submitting = false;
		}
	}
</script>

<svelte:window
	onkeydown={(e) => {
		if (e.key === 'Escape') close();
	}}
/>

<div class="overlay">
	<!-- Click-outside catcher: a sibling of the dialog, not a parent, so it doesn't nest
	     interactive controls inside an interactive element. -->
	<button class="backdrop" tabindex="-1" aria-hidden="true" onclick={close}></button>
	<div
		class="modal"
		role="dialog"
		aria-modal="true"
		aria-labelledby="new-order-title"
		tabindex="-1"
		bind:this={dialog}
	>
		<div class="modal-head">
			<span class="title" id="new-order-title">{ng.orders_new_order_title()}</span>
			<button class="x" onclick={close} aria-label={m['buttons.close']()}><X size={16} /></button>
		</div>

		<form
			class="body"
			onsubmit={(e) => {
				e.preventDefault();
				submit();
			}}
		>
			<FieldGrid labelWidth="140px">
				<Field label={ng.orders_shop()}>
					<Combobox
						value={shopName}
						options={shops}
						placeholder={ng.orders_shop_placeholder()}
						oninput={(v) => (shopName = v)}
					/>
				</Field>
				<Field label={ng.orders_order_date()}>
					<DateTimeField value={orderedAt} oninput={(iso) => (orderedAt = iso)} />
				</Field>
				<Field label={ng.orders_order_number_field()}>
					<EditableField
						value={orderNumber}
						placeholder="e.g. 3DJ-84302"
						oninput={(v) => (orderNumber = v)}
					/>
				</Field>
				<Field label={ng.orders_url()}>
					<EditableField value={url} placeholder="https://..." linkify oninput={(v) => (url = v)} />
				</Field>
				<Field label={ng.orders_comment()}>
					<textarea class="comment" rows="2" bind:value={comment}></textarea>
				</Field>
			</FieldGrid>

			<div class="lines">
				<div class="lines-header">{ng.orders_lines_summary_title()}</div>
				{#each lines as line (line.key)}
					<div class="line">
						<select
							class="sel filament-select"
							value={line.filamentId ?? ''}
							aria-label={ng.orders_select_filament()}
							onchange={(e) => updateLine(line.key, { filamentId: e.currentTarget.value || undefined })}
						>
							<option value="">{ng.orders_select_filament()}</option>
							{#each filamentOptions as opt (opt.id)}
								<option value={opt.id}>{opt.label}</option>
							{/each}
						</select>
						<NumberInput
							value={line.quantity}
							min={1}
							width="80px"
							ariaLabel={ng.orders_quantity()}
							onchange={(v) => updateLine(line.key, { quantity: v })}
						/>
						<NumberInput
							value={line.pricePerUnit ?? ''}
							min={0}
							width="100px"
							placeholder="21.90"
							ariaLabel={ng.orders_price_per_unit()}
							onchange={(v) => updateLine(line.key, { pricePerUnit: v })}
							onclear={() => updateLine(line.key, { pricePerUnit: undefined })}
						/>
						<Button variant="ghost" ariaLabel={ng.orders_remove_line()} onclick={() => removeLine(line.key)}>
							<Trash2 size={14} />
						</Button>
					</div>
				{/each}
				<Button variant="outline" onclick={addLine}>
					<Plus size={14} />
					{ng.orders_add_line()}
				</Button>
			</div>
		</form>

		<div class="foot">
			<Button variant="outline" disabled={submitting} onclick={close}>{m['buttons.cancel']()}</Button>
			<Button variant="primary" disabled={submitting || !orderedAt || !hasValidLine} onclick={submit}>
				{ng.orders_create_order()}
			</Button>
		</div>
	</div>
</div>

<style>
	.overlay {
		position: fixed;
		inset: 0;
		background: rgba(0, 0, 0, 0.6);
		z-index: 60;
		display: flex;
		align-items: flex-start;
		justify-content: center;
		padding: 8vh 16px 16px;
	}
	.backdrop {
		position: fixed;
		inset: 0;
		border: none;
		margin: 0;
		padding: 0;
		background: transparent;
		cursor: default;
	}
	.modal {
		position: relative;
		z-index: 1;
		width: 640px;
		max-width: 100%;
		max-height: 84vh;
		display: flex;
		flex-direction: column;
		background: var(--bg);
		border: 1px solid var(--border-strong);
		border-radius: var(--radius-xl);
		box-shadow: 0 20px 60px rgba(0, 0, 0, 0.6);
		overflow: hidden;
	}
	.modal-head {
		display: flex;
		align-items: center;
		gap: 10px;
		padding: 16px 20px 0;
		flex: none;
	}
	.title {
		font-weight: 700;
		font-size: 15px;
	}
	.x {
		margin-left: auto;
		color: var(--text-dim);
		cursor: pointer;
		padding: 4px 8px;
		background: none;
		border: none;
		display: inline-flex;
	}
	.x:hover {
		color: var(--text);
	}
	.body {
		padding: 14px 20px 4px;
		overflow-y: auto;
	}
	.comment {
		width: 100%;
		border: 1px solid var(--border-strong);
		background: none;
		border-radius: 7px;
		padding: 9px 12px;
		color: var(--text);
		font-size: 13px;
		font-family: inherit;
		resize: vertical;
	}
	.comment:focus {
		outline: none;
		border-color: var(--accent);
	}
	.lines {
		display: flex;
		flex-direction: column;
		gap: 8px;
		margin-top: 18px;
	}
	.lines-header {
		font-size: 11px;
		font-weight: 700;
		text-transform: uppercase;
		letter-spacing: 0.08em;
		color: var(--text-faint);
	}
	.line {
		display: flex;
		align-items: center;
		gap: 8px;
	}
	.filament-select {
		flex: 1 1 200px;
		min-width: 0;
	}
	.sel {
		background: var(--input-bg);
		border: 1px solid var(--border-input);
		border-radius: var(--radius-sm);
		color: var(--text);
		padding: 8px 8px;
		font-size: 13px;
	}
	.foot {
		display: flex;
		justify-content: flex-end;
		gap: 8px;
		padding: 14px 20px 16px;
		flex: none;
	}
</style>
