// client_v2/src/lib/ng/components/OrderDetailsModal.svelte
<script lang="ts">
	// Order details/edit modal (#298) — ported from client/src/pages/orders/orderDetailsModal.tsx:
	// opened by clicking an order row on the Orders list (routes/orders/+page.svelte). Shows the
	// shop, ordered date, order number, url and comment, all editable via the same
	// Combobox/DateTimeField/EditableField pattern as MarkOrderedDialog.svelte. Each line's quantity
	// and price/spool are editable while still outstanding; already-arrived lines render read-only
	// with their arrived state. Saving PATCHes /order/{id}: since the backend fully replaces the
	// line set whenever `lines` is present (see orderEditBody.ts's docstring), every line is sent
	// back — buildEditedLines folds the per-row edits over the order's original lines so arrived
	// ones go out unchanged. Delete removes the order (and cascades its lines) after a confirm,
	// matching FilamentInspector's delete-confirm pattern.
	//
	// The caller mounts this only while an order is actually selected (`{#if detailsOrder}<OrderDetailsModal
	// order={detailsOrder} .../>{/if}`), same as MarkOrderedDialog's own doc comment on why upstream's
	// two order dialogs are conditionally rendered — so every `$state` below is seeded once, from the
	// order this opened with, and there is nothing to reset on a later reopen.
	import { untrack } from 'svelte';
	import Button from '$components/Button.svelte';
	import Field from '$components/Field.svelte';
	import FieldGrid from '$components/FieldGrid.svelte';
	import Combobox from '$components/Combobox.svelte';
	import NumberInput from '$components/NumberInput.svelte';
	import { parseDecimal } from '$lib/utils/numeric';
	import DateTimeField from '$components/DateTimeField.svelte';
	import EditableField from '$components/EditableField.svelte';
	import ConfirmDialog from '$components/ConfirmDialog.svelte';
	import X from '@lucide/svelte/icons/x';
	import Trash2 from '@lucide/svelte/icons/trash-2';
	import * as m from '$lib/paraglide/messages';
	import { ng } from '$lib/ng/i18n';
	import { listShops, ensureShop, updateOrder, deleteOrder } from '$lib/ng/api';
	import { buildEditedLines, buildOrderPatchBody, type LineEdit } from '$lib/ng/orderEditBody';
	import { getFilamentName } from '$lib/ng/analytics';
	import { toasts } from '$lib/stores/toasts.svelte';
	import type { ForkFilament, Order } from '$lib/ng/types';
	import type { Vendor } from '$lib/types';

	interface Props {
		order: Order;
		filaments: ForkFilament[];
		vendors: Vendor[];
		onclose: () => void;
		onsuccess: () => void;
	}
	let { order, filaments, vendors, onclose, onsuccess }: Props = $props();

	// This dialog is only ever mounted fresh for one order (see the module doc comment above), so
	// `order` never changes out from under it — but reading a prop directly in a `$state`
	// initializer still trips Svelte's "state_referenced_locally" check, since in general nothing
	// stops a prop from changing later. `untrack` says that's fine here, the same way
	// CreateOrderModal.svelte's `untrack(() => rows)` does for its own once-only seeding.
	const initial = untrack(() => order);

	let shopName = $state(initial.shop?.name ?? '');
	let shops = $state<string[]>([]);
	let orderedAt = $state<string | undefined>(initial.orderedAt);
	let orderNumber = $state(initial.orderNumber ?? '');
	let url = $state(initial.url ?? '');
	let comment = $state(initial.comment ?? '');
	// Seeded from the still-outstanding lines only — an arrived line is never edited (see
	// buildEditedLines, which passes those through untouched regardless of what's in here).
	//
	// Held as strings and bound live (NumberInput's default mode) rather than as numbers
	// committed on blur. Both work; this way the state here is the single source of truth for
	// what the field shows, so there is no window in which the input holds a value the component
	// has not seen yet.
	let lineDrafts = $state<Record<number, { quantity: string; pricePerUnit: string }>>(
		Object.fromEntries(
			initial.lines
				.filter((l) => !l.arrivedAt)
				.map((l) => [
					l.id,
					{
						quantity: String(l.quantity),
						pricePerUnit: l.pricePerUnit == null ? '' : String(l.pricePerUnit)
					}
				])
		)
	);
	let submitting = $state(false);
	let confirmDeleteOpen = $state(false);
	let deleting = $state(false);

	const orderLabel = initial.orderNumber ?? `#${initial.id}`;

	/** The drafts, parsed back into the numbers buildEditedLines expects. */
	function editsFromDrafts(): Record<number, LineEdit> {
		return Object.fromEntries(
			Object.entries(lineDrafts).map(([id, d]) => {
				const quantity = parseDecimal(d.quantity);
				const price = parseDecimal(d.pricePerUnit);
				return [
					Number(id),
					{
						// A blank or unparseable quantity keeps the line rather than deleting it: 1 is
						// the smallest the API accepts, and silently dropping a line here would be a
						// destructive reading of a typo.
						quantity: quantity == null || quantity < 1 ? 1 : quantity,
						pricePerUnit: price == null ? undefined : price
					}
				];
			})
		);
	}

	let dialog = $state<HTMLDivElement>();
	let opener: HTMLElement | null = null;
	$effect(() => {
		opener = document.activeElement as HTMLElement | null;
		dialog?.focus();
		listShops()
			.then((s) => (shops = s.map((sh) => sh.name)))
			.catch(() => (shops = []));
		return () => opener?.focus();
	});

	function close() {
		if (!submitting && !deleting) onclose();
	}

	async function submit() {
		if (submitting || !orderedAt) return;
		submitting = true;
		try {
			const name = shopName.trim();
			const shopId = name ? await ensureShop(name) : null;
			const lines = buildEditedLines(order.lines, editsFromDrafts());
			const body = buildOrderPatchBody({ shopId, orderedAt, orderNumber, url, comment }, lines);
			await updateOrder(order.id, body);
			onsuccess();
			onclose();
		} catch (e) {
			console.error('Failed to update order', e);
			toasts.error(ng.orders_update_error());
		} finally {
			submitting = false;
		}
	}

	async function confirmDelete() {
		deleting = true;
		try {
			await deleteOrder(order.id);
			onsuccess();
			onclose();
		} catch (e) {
			console.error('Failed to delete order', e);
			toasts.error(ng.orders_delete_error());
			confirmDeleteOpen = false;
		} finally {
			deleting = false;
		}
	}
</script>

<svelte:window
	onkeydown={(e) => {
		// Ignored while the delete confirm is open: both dialogs listen on `window`, and
		// stopPropagation() in ConfirmDialog wouldn't stop this sibling listener from also
		// firing (it only prevents bubbling past the target, not other listeners on it) — so
		// this guard is what keeps Escape from closing both at once.
		if (e.key === 'Escape' && !confirmDeleteOpen) close();
	}}
/>

<div class="overlay">
	<!-- Click-outside catcher: a sibling of the dialog, not a parent, so it doesn't nest
	     interactive controls inside an interactive element. -->
	<button class="backdrop" tabindex="-1" aria-hidden="true" onclick={close}></button>
	<div
		class="modal"
		role="dialog"
		aria-modal="true"
		aria-labelledby="order-details-title"
		tabindex="-1"
		bind:this={dialog}
	>
		<div class="modal-head">
			<span class="title" id="order-details-title">
				{ng.orders_details_title({ number: orderLabel })}
			</span>
			<button class="x" onclick={close} aria-label={m['buttons.close']()}><X size={16} /></button>
		</div>

		<form
			class="body"
			onsubmit={(e) => {
				e.preventDefault();
				submit();
			}}
		>
			<FieldGrid labelWidth="140px">
				<Field label={ng.orders_shop()}>
					<Combobox
						value={shopName}
						options={shops}
						placeholder={ng.orders_shop_placeholder()}
						oninput={(v) => (shopName = v)}
					/>
				</Field>
				<Field label={ng.orders_order_date()}>
					<DateTimeField value={orderedAt} oninput={(iso) => (orderedAt = iso)} />
				</Field>
				<Field label={ng.orders_order_number_field()}>
					<EditableField
						value={orderNumber}
						placeholder="e.g. 3DJ-84302"
						oninput={(v) => (orderNumber = v)}
					/>
				</Field>
				<Field label={ng.orders_url()}>
					<EditableField value={url} placeholder="https://..." linkify oninput={(v) => (url = v)} />
				</Field>
				<Field label={ng.orders_comment()}>
					<textarea class="comment" rows="2" bind:value={comment}></textarea>
				</Field>
			</FieldGrid>

			<div class="lines">
				<div class="lines-header">{ng.orders_lines_summary_title()}</div>
				{#each order.lines as line (line.id)}
					{@const filament = filaments.find((f) => f.id === line.filamentId)}
					{@const name = filament ? getFilamentName(filament, vendors) : `#${line.filamentId}`}
					{#if line.arrivedAt}
						<div class="line arrived">
							<span class="line-name">{name}</span>
							<span class="line-qty">× {line.quantity}</span>
							<span class="line-price">{line.pricePerUnit != null ? line.pricePerUnit : '—'}</span>
							<span class="line-state check">✓ {ng.orders_state_arrived()}</span>
						</div>
					{:else}
						<div class="line">
							<span class="line-name">{name}</span>
							<NumberInput
								bind:value={lineDrafts[line.id].quantity}
								min={1}
								width="80px"
								ariaLabel={`${ng.orders_quantity()} — ${name}`}
							/>
							<NumberInput
								bind:value={lineDrafts[line.id].pricePerUnit}
								min={0}
								width="100px"
								placeholder="21.90"
								ariaLabel={`${ng.orders_price_per_unit()} — ${name}`}
							/>
							<span class="line-state">{ng.orders_outstanding()}</span>
						</div>
					{/if}
				{/each}
			</div>
		</form>

		<div class="foot">
			<Button
				variant="danger-ghost"
				disabled={submitting || deleting}
				onclick={() => (confirmDeleteOpen = true)}
			>
				<Trash2 size={14} />
				{m['buttons.delete']()}
			</Button>
			<span class="spacer"></span>
			<Button variant="outline" disabled={submitting || deleting} onclick={close}>
				{m['buttons.cancel']()}
			</Button>
			<Button variant="primary" disabled={submitting || deleting || !orderedAt} onclick={submit}>
				{m['buttons.save']()}
			</Button>
		</div>
	</div>
</div>

<ConfirmDialog
	open={confirmDeleteOpen}
	busy={deleting}
	title={orderLabel}
	lines={[ng.orders_delete_confirm()]}
	confirmLabel={m['buttons.delete']()}
	onconfirm={confirmDelete}
	onclose={() => (confirmDeleteOpen = false)}
/>

<style>
	.overlay {
		position: fixed;
		inset: 0;
		background: rgba(0, 0, 0, 0.6);
		z-index: 60;
		display: flex;
		align-items: flex-start;
		justify-content: center;
		padding: 8vh 16px 16px;
	}
	.backdrop {
		position: fixed;
		inset: 0;
		border: none;
		margin: 0;
		padding: 0;
		background: transparent;
		cursor: default;
	}
	.modal {
		position: relative;
		z-index: 1;
		width: 640px;
		max-width: 100%;
		max-height: 84vh;
		display: flex;
		flex-direction: column;
		background: var(--bg);
		border: 1px solid var(--border-strong);
		border-radius: var(--radius-xl);
		box-shadow: 0 20px 60px rgba(0, 0, 0, 0.6);
		overflow: hidden;
	}
	.modal-head {
		display: flex;
		align-items: center;
		gap: 10px;
		padding: 16px 20px 0;
		flex: none;
	}
	.title {
		font-weight: 700;
		font-size: 15px;
	}
	.x {
		margin-left: auto;
		color: var(--text-dim);
		cursor: pointer;
		padding: 4px 8px;
		background: none;
		border: none;
		display: inline-flex;
	}
	.x:hover {
		color: var(--text);
	}
	.body {
		padding: 14px 20px 4px;
		overflow-y: auto;
	}
	.comment {
		width: 100%;
		border: 1px solid var(--border-strong);
		background: none;
		border-radius: 7px;
		padding: 9px 12px;
		color: var(--text);
		font-size: 13px;
		font-family: inherit;
		resize: vertical;
	}
	.comment:focus {
		outline: none;
		border-color: var(--accent);
	}
	.lines {
		display: flex;
		flex-direction: column;
		gap: 8px;
		margin-top: 18px;
	}
	.lines-header {
		font-size: 11px;
		font-weight: 700;
		text-transform: uppercase;
		letter-spacing: 0.08em;
		color: var(--text-faint);
	}
	.line {
		display: flex;
		align-items: center;
		gap: 10px;
		flex-wrap: wrap;
		padding: 6px 0;
		border-top: 1px solid var(--hairline);
	}
	.line:first-child {
		border-top: none;
	}
	.line.arrived {
		opacity: 0.55;
	}
	.line-name {
		flex: 1 1 auto;
		min-width: 0;
		overflow: hidden;
		text-overflow: ellipsis;
		white-space: nowrap;
		font-size: 12.5px;
	}
	.line-qty,
	.line-price {
		font-size: 12.5px;
		color: var(--text-dim);
		white-space: nowrap;
	}
	.line-state {
		white-space: nowrap;
		font-size: 11.5px;
		color: var(--text-faint);
	}
	.line-state.check {
		color: var(--success);
	}
	.foot {
		display: flex;
		align-items: center;
		gap: 8px;
		padding: 14px 20px 16px;
		flex: none;
	}
	.spacer {
		flex: 1;
	}
</style>

// client/src/pages/orders/orderDetailsModal.tsx
import { DeleteOutlined } from "@ant-design/icons";
import { useDelete, useInvalidate, useTranslate, useUpdate } from "@refinedev/core";
import { AutoComplete, Button, Col, DatePicker, Form, Input, InputNumber, message, Modal, Row } from "antd";
import { useForm } from "antd/es/form/Form";
import dayjs, { Dayjs } from "dayjs";
import utc from "dayjs/plugin/utc";
import { useEffect, useRef, useState } from "react";
import { DATE_FORMAT } from "../../utils/dateFormat";
import { safeHttpUrl } from "../../utils/url";
import { getFilamentName } from "../home/analytics";
import { IFilament } from "../filaments/model";
import { buildEditedLines, buildOrderPatchBody, LineEdit } from "./orderEditBody";
import { IOrder } from "./model";
import { useShops } from "./useShops";
import "./orders.css";

dayjs.extend(utc);

interface DetailsFormValues {
  shop_name?: string;
  ordered_at: Dayjs;
  order_number?: string;
  url?: string;
  comment?: string;
}

interface Props {
  open: boolean;
  order?: IOrder;
  filamentsById: Map<number, IFilament>;
  onClose: () => void;
  onSuccess: () => void;
}

/**
 * Order details/edit modal (gate-feedback item #5): opened by clicking an order row (or its
 * order # link) on the Orders list — replaces the old antd Table row-expander. Shows the shop,
 * ordered date, order number, url (as a safe link — see safeHttpUrl's docstring) and comment, all
 * editable via the same shop-AutoComplete/DatePicker pattern as markOrderedDialog.tsx. Each line's
 * quantity and price/spool are editable while still outstanding; already-arrived lines render
 * read-only with their arrived state. Saving PATCHes /order/{id}: since the backend fully replaces
 * the line set whenever `lines` is present (see orderEditBody.ts's docstring), every line is sent
 * back — buildEditedLines folds the per-row edits over the order's original lines so arrived ones
 * go out unchanged. Delete removes the order (and cascades its lines) after a confirm, matching
 * the spools/show.tsx delete pattern.
 */
export function OrderDetailsModal({ open, order, filamentsById, onClose, onSuccess }: Props) {
  const t = useTranslate();
  const [form] = useForm<DetailsFormValues>();
  const { shops, ensureShop } = useShops();
  const { mutate: updateOrder, mutation: updateMutation } = useUpdate();
  const { mutate: deleteOrder, mutation: deleteMutation } = useDelete();
  const invalidate = useInvalidate();
  const [submitting, setSubmitting] = useState(false);
  const [lineEdits, setLineEdits] = useState<Record<number, LineEdit>>({});
  // Guards the open:false→true transition only (same convention as createOrderModal.tsx's
  // wasOpenRef) — a background refetch of the order/filament lists while this stays open must not
  // reset the form or wipe edits the user already made.
  const wasOpenRef = useRef(false);

  useEffect(() => {
    if (open && !wasOpenRef.current && order) {
      form.resetFields();
      form.setFieldsValue({
        shop_name: order.shop?.name,
        ordered_at: dayjs(order.ordered_at),
        order_number: order.order_number,
        url: order.url,
        comment: order.comment,
      });
      setLineEdits(
        Object.fromEntries(
          order.lines
            .filter((l) => !l.arrived_at)
            .map((l) => [l.id, { quantity: l.quantity, price_per_unit: l.price_per_unit }]),
        ),
      );
    }
    wasOpenRef.current = open;
  }, [open, order, form]);

  if (!order) return null;

  const shopOptions = shops.map((s) => ({ value: s.name }));
  const orderLabel = order.order_number ?? `#${order.id}`;
  const href = safeHttpUrl(order.url);

  const invalidateAfterChange = () => {
    invalidate({ resource: "order", invalidates: ["list"] });
    invalidate({ resource: "filament", invalidates: ["list"] });
    invalidate({ resource: "spool", invalidates: ["list"] });
  };

  const onFinish = async (values: DetailsFormValues) => {
    setSubmitting(true);
    try {
      const name = values.shop_name?.trim();
      const shopId = name ? await ensureShop(name) : null;
      const lines = buildEditedLines(order.lines, lineEdits);
      const body = buildOrderPatchBody(
        {
          shopId,
          orderedAt: values.ordered_at.utc().format(),
          orderNumber: values.order_number ?? "",
          url: values.url ?? "",
          comment: values.comment ?? "",
        },
        lines,
      );
      updateOrder(
        { resource: "order", id: order.id, values: body, successNotification: false },
        {
          onSuccess: () => {
            invalidateAfterChange();
            setSubmitting(false);
            onSuccess();
            onClose();
          },
          onError: () => {
            setSubmitting(false);
            message.error(t("orders.update_error"));
          },
        },
      );
    } catch {
      setSubmitting(false);
      message.error(t("orders.update_error"));
    }
  };

  const handleDelete = () => {
    Modal.confirm({
      title: t("buttons.confirm"),
      content: t("orders.delete_confirm"),
      okText: t("buttons.delete"),
      okType: "danger",
      cancelText: t("buttons.cancel"),
      onOk: () =>
        new Promise<void>((resolve, reject) => {
          deleteOrder(
            { resource: "order", id: order.id, successNotification: false },
            {
              onSuccess: () => {
                invalidateAfterChange();
                resolve();
                onSuccess();
                onClose();
              },
              onError: (error) => {
                message.error(t("orders.delete_error"));
                reject(error);
              },
            },
          );
        }),
    });
  };

  return (
    <Modal
      title={t("orders.details_title", { number: orderLabel })}
      open={open}
      onCancel={onClose}
      destroyOnClose
      width={640}
      footer={[
        <Button key="delete" danger icon={<DeleteOutlined />} loading={deleteMutation.isPending} onClick={handleDelete}>
          {t("buttons.delete")}
        </Button>,
        <Button key="cancel" onClick={onClose}>
          {t("buttons.cancel")}
        </Button>,
        <Button
          key="save"
          type="primary"
          loading={submitting || updateMutation.isPending}
          onClick={() => form.submit()}
        >
          {t("buttons.save")}
        </Button>,
      ]}
    >
      <Form form={form} layout="vertical" onFinish={onFinish}>
        <Row gutter={16}>
          <Col xs={24} md={12}>
            <Form.Item name="shop_name" label={t("orders.shop")}>
              <AutoComplete
                options={shopOptions}
                filterOption={(input, option) => (option?.value ?? "").toLowerCase().includes(input.toLowerCase())}
                placeholder={t("orders.shop_placeholder")}
              />
            </Form.Item>
          </Col>
          <Col xs={24} md={12}>
            <Form.Item name="ordered_at" label={t("orders.order_date")} rules={[{ required: true }]}>
              <DatePicker style={{ width: "100%" }} format={DATE_FORMAT} allowClear={false} />
            </Form.Item>
          </Col>
        </Row>
        <Row gutter={16}>
          <Col xs={24} md={12}>
            <Form.Item name="order_number" label={t("orders.order_number_field")}>
              <Input maxLength={256} />
            </Form.Item>
          </Col>
          <Col xs={24} md={12}>
            <Form.Item name="url" label={t("orders.url")}>
              <Input placeholder="https://..." maxLength={1024} />
            </Form.Item>
          </Col>
        </Row>
        <Form.Item name="comment" label={t("orders.comment")}>
          <Input.TextArea maxLength={1024} rows={2} />
        </Form.Item>
      </Form>
      {href && (
        <div className="order-details-link">
          <a href={href} target="_blank" rel="noreferrer noopener">
            {href}
          </a>
        </div>
      )}
      <div className="order-details-lines">
        <div className="order-details-lines-header">{t("orders.lines_summary_title")}</div>
        {order.lines.map((line) => {
          const filament = filamentsById.get(line.filament_id);
          const name = filament ? getFilamentName(filament) : `#${line.filament_id}`;

          if (line.arrived_at) {
            return (
              <div key={line.id} className="order-details-line order-details-line-arrived">
                <span className="order-details-line-name">{name}</span>
                <span className="order-details-line-qty">× {line.quantity}</span>
                <span className="order-details-line-price">
                  {line.price_per_unit != null ? line.price_per_unit : "—"}
                </span>
                <span className="order-details-line-state">✓ {t("orders.state.arrived")}</span>
              </div>
            );
          }

          const edit = lineEdits[line.id] ?? { quantity: line.quantity, price_per_unit: line.price_per_unit };
          return (
            <div key={line.id} className="order-details-line">
              <span className="order-details-line-name">{name}</span>
              <InputNumber
                min={1}
                value={edit.quantity}
                aria-label={t("orders.quantity")}
                onChange={(v) => setLineEdits((prev) => ({ ...prev, [line.id]: { ...edit, quantity: v ?? 1 } }))}
              />
              <InputNumber
                min={0}
                value={edit.price_per_unit}
                placeholder="21.90"
                aria-label={t("orders.price_per_unit")}
                onChange={(v) =>
                  setLineEdits((prev) => ({ ...prev, [line.id]: { ...edit, price_per_unit: v ?? undefined } }))
                }
              />
              <span className="order-details-line-state">{t("orders.outstanding")}</span>
            </div>
          );
        })}
      </div>
    </Modal>
  );
}

export default OrderDetailsModal;
